"""Phrase-correction data for the grammar checker.

Auto-generated from Harper's `phrase_set_corrections` rule set
(https://github.com/Automattic/harper, Apache-2.0). Each entry maps a
non-standard phrase to one or more suggested corrections. Do not edit by
hand; regenerate with tools/generate_phrase_data.py. See NOTICE.
"""

# bad phrase (lower-case, single-spaced) -> list of suggested corrections
PHRASE_CORRECTIONS = {
    'a bridge to far': ['a bridge too far'],
    'a certain extend': ['a certain extent'],
    'a lot worst': ['a lot worse'],
    'a side tangent': ['a tangent', 'an aside'],
    'a whole entire': ['a whole', 'an entire'],
    'algo': ['algorithm'],
    'algos': ['algorithms'],
    'alloc': ['allocate', 'allocation'],
    'allocs': ['allocates', 'allocations'],
    'alot worst': ['a lot worse'],
    'am use to': ['am used to'],
    'an escape goat': ['a scapegoat'],
    'are use to': ['are used to'],
    'arg': ['argument'],
    'args': ['arguments'],
    'argument to be said': ['argument to be made'],
    'arguments to be said': ['arguments to be made'],
    'arise the question': ['raise the question'],
    'arises the question': ['raises the question'],
    'arising the question': ['raising the question'],
    'assume responsibility of': ['assume responsibility for'],
    'assumed responsibility of': ['assumed responsibility for'],
    'assumes responsibility of': ['assumes responsibility for'],
    'assuming responsibility of': ['assuming responsibility for'],
    'at worse': ['at worst'],
    'await for': ['await', 'wait for'],
    'awaited for': ['awaited', 'waited for'],
    'awaiting for': ['awaiting', 'waiting for'],
    'awaits for': ['awaits', 'waits for'],
    'be use to': ['be used to'],
    'became worst': ['became worse'],
    'become worst': ['become worse'],
    'becomes worst': ['becomes worse'],
    'becoming worst': ['becoming worse'],
    'bullocks!': ['bollocks!'],
    'by wrote': ['by rote'],
    'by-wrote': ['by-rote'],
    'cake and eat it to': ['cake and eat it too'],
    'chomp at the bit': ['champ at the bit'],
    'chomped at the bit': ['champed at the bit'],
    'chomping at the bit': ['champing at the bit'],
    'chomps at the bit': ['champs at the bit'],
    'claim responsibility of': ['claim responsibility for'],
    'claimed responsibility of': ['claimed responsibility for'],
    'claiming responsibility of': ['claiming responsibility for'],
    'claims responsibility of': ['claims responsibility for'],
    "client's side": ['client-side'],
    'commitment toward': ['commitment to'],
    'commitment towards': ['commitment to'],
    'commitments toward': ['commitments to'],
    'commitments towards': ['commitments to'],
    'complete bullocks': ['complete bollocks'],
    'compulse': ['compel'],
    'compulsed': ['compelled'],
    'compulses': ['compels'],
    'compulsing': ['compelling'],
    'conform that': ['confirm that'],
    'conformed that': ['confirmed that'],
    'conforming that': ['confirming that'],
    'conforms that': ['confirms that'],
    'constitute as': ['constitute'],
    'constituted as': ['constituted'],
    'constitutes as': ['constitutes'],
    'constituting as': ['constituting'],
    'coord': ['coordinate'],
    'coords': ['coordinates'],
    'copywrite': ['copyright'],
    'copywrited': ['copyrighted'],
    'copywrites': ['copyrights'],
    'copywriting': ['copyrighting'],
    'copywritten': ['copyrighted'],
    'copywrote': ['copyrighted'],
    'date back from': ['date from', 'date back to'],
    'dates back from': ['dates from', 'dates back to'],
    'decl': ['declaration', 'declarator'],
    'decls': ['declarations', 'declarators'],
    'definitive article': ['definite article'],
    'definitive articles': ['definite articles'],
    'dep': ['dependency'],
    'deps': ['dependencies'],
    'deref': ['dereference'],
    'derefs': ['dereferences'],
    'digestive track': ['digestive tract'],
    'digestive tracks': ['digestive tracts'],
    'discuss about': ['discuss'],
    'discussed about': ['discussed'],
    'discusses about': ['discusses'],
    'discussing about': ['discussing'],
    "dog's bullocks": ["dog's bollocks"],
    'dogs bullocks': ['dogs bollocks'],
    'dose not': ['does not'],
    'double edge sword': ['double-edged sword'],
    'double edge swords': ['double-edged swords'],
    'double edge-sword': ['double-edged sword'],
    'double edge-swords': ['double-edged swords'],
    'double edged sword': ['double-edged sword'],
    'double edged swords': ['double-edged swords'],
    'double edged-sword': ['double-edged sword'],
    'double edged-swords': ['double-edged swords'],
    'double-edge sword': ['double-edged sword'],
    'double-edge swords': ['double-edged swords'],
    'double-edge-sword': ['double-edged sword'],
    'double-edge-swords': ['double-edged swords'],
    'double-edged-sword': ['double-edged sword'],
    'double-edged-swords': ['double-edged swords'],
    'escape goat': ['scapegoat'],
    'escape goats': ['scapegoats'],
    'everybody seams': ['everybody seems'],
    'everyone seams': ['everyone seems'],
    'everything seams': ['everything seems'],
    'ex pat': ['expat'],
    "ex pat's": ["expat's"],
    'ex patriot': ['expatriate'],
    "ex patriot's": ["expatriate's"],
    'ex patriots': ['expatriates'],
    'ex pats': ['expats'],
    'ex-pat': ['expat'],
    "ex-pat's": ["expat's"],
    'ex-patriot': ['expatriate'],
    "ex-patriot's": ["expatriate's"],
    'ex-patriots': ['expatriates'],
    'ex-pats': ['expats'],
    'expatriot': ['expatriate'],
    "expatriot's": ["expatriate's"],
    'expatriots': ['expatriates'],
    'explanation mark': ['exclamation mark'],
    'explanation marks': ['exclamation marks'],
    'explanation point': ['exclamation point'],
    'far worst': ['far worse'],
    'flaunt authority': ['flout authority'],
    'flaunt convention': ['flout convention'],
    'flaunt the law': ['flout the law'],
    'flaunt the regulations': ['flout the regulations'],
    'flaunt the rules': ['flout the rules'],
    'flaunted authority': ['flouted authority'],
    'flaunted convention': ['flouted convention'],
    'flaunted the law': ['flouted the law'],
    'flaunted the rules': ['flouted the rules'],
    'flaunting authority': ['flouting authority'],
    'flaunting convention': ['flouting convention'],
    'flaunting the law': ['flouting the law'],
    'flaunting the rules': ['flouting the rules'],
    'flaunts authority': ['flouts authority'],
    'flaunts convention': ['flouts convention'],
    'flaunts the law': ['flouts the law'],
    'flaunts the rules': ['flouts the rules'],
    'flip the bill': ['foot the bill'],
    'flipped the bill': ['footed the bill'],
    'flipping the bill': ['footing the bill'],
    'flips the bill': ['foots the bill'],
    'foam out the mouth': ['foam at the mouth'],
    'foamed out the mouth': ['foamed at the mouth'],
    'foaming out the mouth': ['foaming at the mouth'],
    'foams out the mouth': ['foams at the mouth'],
    'further adieu': ['further ado'],
    'get rid off': ['get rid of'],
    'get ride of': ['get rid of'],
    'get ride off': ['get rid of'],
    'get use to': ['get used to'],
    'get used of': ['get used to'],
    'get worst': ['get worse'],
    'gets rid off': ['gets rid of'],
    'gets ride of': ['gets rid of'],
    'gets ride off': ['gets rid of'],
    'gets used of': ['gets used to'],
    'gets worst': ['gets worse'],
    'getting rid off': ['getting rid of'],
    'getting ride of': ['getting rid of'],
    'getting ride off': ['getting rid of'],
    'getting use to': ['getting used to'],
    'getting used of': ['getting used to'],
    'getting worst': ['getting worse'],
    'go to far': ['go too far'],
    'goes to far': ['goes too far'],
    'going to far': ['going too far'],
    'gone to far': ['gone too far'],
    'got rid off': ['got rid of'],
    'got ride of': ['got rid of'],
    'got ride off': ['got rid of'],
    'got use to': ['got used to'],
    'got used of': ['got used to'],
    'got worst': ['got worse'],
    'gotten rid off': ['gotten rid of'],
    'gotten ride of': ['gotten rid of'],
    'gotten ride off': ['gotten rid of'],
    'gotten used of': ['gotten used to'],
    'gotten worst': ['gotten worse'],
    'govt': ['government'],
    'govt.': ['government'],
    'govts': ['governments'],
    'grind to halt': ['grind to a halt'],
    'grinding to halt': ['grinding to a halt'],
    'grinds to halt': ['grinds to a halt'],
    'ground to halt': ['ground to a halt'],
    'had past': ['had passed'],
    'has past': ['has passed'],
    'have past': ['have passed'],
    'having past': ['having passed'],
    'he dose': ['he does'],
    'he seams': ['he seems'],
    "he's use to": ["he's used to"],
    'hit the nail in the head': ['hit the nail on the head'],
    'hits the nail in the head': ['hits the nail on the head'],
    'hitted the nail in the head': ['hitted the nail on the head'],
    'hitting the nail in the head': ['hitting the nail on the head'],
    'holey war': ['holy war'],
    'holey wars': ['holy wars'],
    'holly war': ['holy war'],
    'holly wars': ['holy wars'],
    'hone in on': ['home in on'],
    'honed in on': ['homed in on'],
    'hones in on': ['homes in on'],
    'honing in on': ['homing in on'],
    'how dose': ['how does'],
    'how he looks like': ['how he looks', 'what he looks like'],
    'how it look like': ['how it looks', 'what it looks like'],
    "how it look's like": ['how it looks', 'what it looks like'],
    'how it looks like': ['how it looks', 'what it looks like'],
    'how she looks like': ['how she looks', 'what she looks like'],
    'how they look like': ['how they look', 'what they look like'],
    'how they looks like': ['how they look', 'what they look like'],
    'i seam': ['i seem'],
    'i wish he was': ['i wish he were'],
    'i wish i was': ['i wish i were'],
    'i wish it was': ['i wish it were'],
    'i wish she was': ['i wish she were'],
    'i wish there was': ['i wish there were'],
    "i'm use to": ["i'm used to"],
    'if only he was': ['if only he were'],
    'if only i was': ['if only i were'],
    'if only it was': ['if only it were'],
    'if only she was': ['if only she were'],
    'if only there was': ['if only there were'],
    'in details': ['in detail'],
    'in more details': ['in more detail'],
    'infliction point': ['inflection point'],
    'infliction points': ['inflection points'],
    'invest into': ['invest in'],
    'invested into': ['invested in'],
    'investing into': ['investing in'],
    'investment into': ['investment in'],
    'invests into': ['invests in'],
    'is bullocks': ['is bollocks'],
    'is use to': ['is used to'],
    'it dose': ['it does'],
    'it seams': ['it seems'],
    "it's bullocks": ["it's bollocks"],
    "it's use to": ["it's used to"],
    'its bullocks': ['its bollocks'],
    'layouted': ['laid out'],
    'layouting': ['laying out'],
    'life is to short': ['life is too short'],
    "life's to short": ["life's too short"],
    'lifes to short': ["life's too short"],
    'look forward for': ['look forward to'],
    'looked forward for': ['looked forward to'],
    'looking forward for': ['looking forward to'],
    'looks forward for': ['looks forward to'],
    'made due with': ['made do with'],
    'made it seemed': ['made it seem'],
    'made it seems': ['made it seem'],
    'made it worst': ['made it worse'],
    'made senses': ['made sense'],
    'made them worst': ['made them worse'],
    'make due with': ['make do with'],
    'make it seems': ['make it seem'],
    'make it worst': ['make it worse'],
    'make senses': ['make sense'],
    'make them worst': ['make them worse'],
    'makes due with': ['makes do with'],
    'makes it seems': ['makes it seem'],
    'makes it worst': ['makes it worse'],
    'makes senses': ['makes sense'],
    'makes them worst': ['makes them worse'],
    'making due with': ['making do with'],
    'making it seems': ['making it seem'],
    'making it worst': ['making it worse'],
    'making senses': ['making sense'],
    'making them worst': ['making them worse'],
    'monumentous': ['momentous', 'monumental'],
    'monumentously': ['momentously', 'monumentally'],
    'more ideal': ['ideal'],
    'more optimal': ['optimal'],
    'more preferable': ['preferable'],
    'most ideal': ['ideal'],
    'most optimal': ['optimal'],
    'much adieu': ['much ado'],
    'much worst': ['much worse'],
    'mute point': ['moot point'],
    'nerve wreck': ['nervous wreck'],
    'nerve wrecks': ['nervous wrecks'],
    'nerve-wreck': ['nervous wreck'],
    'nerve-wrecks': ['nervous wrecks'],
    'no only are': ['not only are'],
    'no only is': ['not only is'],
    'no only was': ['not only was'],
    'no only were': ['not only were'],
    'not impossible': ['possible'],
    'not inaccurate': ['accurate'],
    'not inadequate': ['adequate'],
    'not infrequent': ['frequent'],
    'not insignificant': ['significant'],
    'not irrelevant': ['relevant'],
    'not offline': ['online'],
    'not online': ['offline'],
    'not unclear': ['clear'],
    'not uncommon': ['common'],
    'not unimportant': ['important'],
    'not unlikely': ['likely'],
    'not unpleasant': ['pleasant'],
    'not unpredictable': ['predictable'],
    'not unreasonable': ['reasonable'],
    'not unusual': ['common'],
    'notif': ['notification'],
    'notifs': ['notifications'],
    'operative system': ['operating system'],
    'operative systems': ['operating systems'],
    'overpayed': ['overpaid'],
    'param': ['parameter'],
    'params': ['parameters'],
    'passer-bys': ['passers-by'],
    'passerbys': ['passersby'],
    'payed': ['paid'],
    'peak behind the curtain': ['peek behind the curtain'],
    'peaked behind the curtain': ['peeked behind the curtain'],
    'peaking behind the curtain': ['peeking behind the curtain'],
    'peaks behind the curtain': ['peeks behind the curtain'],
    'piggy bag': ['piggyback'],
    'piggy bagged': ['piggybacked'],
    'piggy bagging': ['piggybacking'],
    'point is mute': ['point is moot'],
    'ptr': ['pointer'],
    'ptrs': ['pointers'],
    'rise the question': ['raise the question'],
    'rises the question': ['raises the question'],
    'rising the question': ['raising the question'],
    'seam to be': ['seem to be'],
    'seams to be': ['seems to be'],
    "server's side": ['server-side'],
    'she dose': ['she does'],
    'she seams': ['she seems'],
    "she's use to": ["she's used to"],
    'side tangent': ['tangent', 'aside'],
    'side tangents': ['tangents', 'aside'],
    'someone dose': ['someone does'],
    'speak to soon': ['speak too soon'],
    'speaking to soon': ['speaking too soon'],
    'spoke to soon': ['spoke too soon'],
    'spoken to soon': ['spoken too soon'],
    'stderr': ['standard error'],
    'stdin': ['standard input'],
    'stdout': ['standard output'],
    'such bullocks': ['such bollocks'],
    'take responsibility of': ['take responsibility for'],
    'taken responsibility of': ['taken responsibility for'],
    'takes responsibility of': ['takes responsibility for'],
    'taking responsibility of': ['taking responsibility for'],
    "that's bullocks": ["that's bollocks"],
    'thats bullocks': ['thats bollocks'],
    'they all seam': ['they all seem'],
    'they both seam': ['they both seem'],
    'they seam': ['they seem'],
    "they're use to": ["they're used to"],
    'think to much': ['think too much'],
    'to an extend': ['to an extent'],
    'to big for': ['too big for'],
    'to big to fail': ['too big to fail'],
    'to good to be true': ['too good to be true'],
    'to much information': ['too much information'],
    'to some extend': ['to some extent'],
    'to the extend that': ['to the extent that'],
    'too big too fail': ['too big to fail'],
    'too good too be true': ['too good to be true'],
    'took responsibility of': ['took responsibility for'],
    'total bullocks': ['total bollocks'],
    'turn for the worst': ['turn for the worse'],
    'utter bullocks': ['utter bollocks'],
    'verse against': ['play against'],
    'verse her': ['play her'],
    'verse him': ['play him'],
    'verse me': ['play me'],
    'verse them': ['play them'],
    'verse you': ['play you'],
    'versed against': ['played against'],
    'verses against': ['plays against'],
    'versing against': ['playing against'],
    'vuln': ['vulnerability'],
    'vulns': ['vulnerabilities'],
    'was bullocks': ['was bollocks'],
    'was use to': ['was used to'],
    'we all seam': ['we all seem'],
    'we both seam': ['we both seem'],
    'we seam': ['we seem'],
    "we're use to": ["we're used to"],
    'went to far': ['went too far'],
    'were use to': ['were used to'],
    'what bullocks': ['what bollocks'],
    'when dose': ['when does'],
    'where dose': ['where does'],
    'who dose': ['who does'],
    'whole entire': ['whole', 'entire'],
    'why dose': ['why does'],
    'worse and worst': ['worse and worse'],
    'worse case scenario': ['worst-case scenario'],
    'worse ever': ['worst ever'],
    'worse-case scenario': ['worst-case scenario'],
    'worse-case-scenario': ['worst-case scenario'],
    'worst and worse': ['worse and worse'],
    'worst and worst': ['worse and worse'],
    'worst than': ['worse than'],
    'wreck havoc': ['wreak havoc'],
    'wrecked havoc': ['wreaked havoc'],
    'wrecking havoc': ['wreaking havoc'],
    'wrecks havoc': ['wreaks havoc'],
    'wrote learning': ['rote learning'],
    'wrote memorisation': ['rote memorisation'],
    'wrote memorization': ['rote memorization'],
    'wrote memorizing': ['rote memorizing'],
    'wrote-memorisation': ['rote-memorisation'],
    'wrote-memorization': ['rote-memorization'],
    'you all seam': ['you all seem'],
    'you both seam': ['you both seem'],
    'you seam': ['you seem'],
    "you're use to": ["you're used to"],
}
